GET http://localhost:8080/api/panels/@me
Accept: application/json
Authorization: Bearer
###

POST http://localhost:8090/api/v1/users/login
Content-Type: application/json

{
  "email": "MrRager@gmail.com"
}
###

POST http://localhost:8080/api/v1/users/create
Content-Type: application/json
Authorization: Basic dfkdfjsghlskhsdflhsdflhjsf

{
  "name": "Jack Frost",
  "username":"NopeVille",
  "email":"MrRager@gmail.com",
  "password":"friday"
}
###

GET http://localhost:8080/api/v1/panels/@me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hyaXN0aWFuIiwiZW1haWwiOiJjbGFyY29tYkBnb29ncy5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRFSndKTU5XVUlmSnc5SWpqVXhWaVEueVZtYVY3dHYwZ0p3UzJOdG50QXFkY2ZZMXh6azZvcSIsImlhdCI6MTU4OTY3MDg4Mn0.kSltBA8PfVkfRL-piVF3ErvrMDknBGvh8Af744VfK58
###

GET http://localhost:8090/api/v1/authentication/gen/access-token
Accept: application/json
Authorization: Bearer